language: ruby

script: bundle exec rake

bundler_args: --without docs release benchmark

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.1
  - jruby-19mode
  - jruby-9.1.2.0

gemfile:
  - gemfiles/no-deps.gemfile
  - gemfiles/json-latest.gemfile
  - gemfiles/json-old.gemfile
  - gemfiles/json-pure.gemfile

matrix:
  exclude:
    # latest version of `json` gem, 2.0+, is not supported on Ruby 1.9.3
    - rvm: 1.9.3
      gemfile: gemfiles/json-latest.gemfile

cache:
  bundler: true
  directories:
    - $HOME/.m2

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d9967f9fc130ccb637a9
    on_success: change
    on_failure: always
    on_start: false
